# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PySide2GUI/ui/WubaGUI.ui',
# licensing of 'PySide2GUI/ui/WubaGUI.ui' applies.
#
# Created: Sun Nov 10 10:19:12 2019
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1080, 720)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1081, 721))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gRoot = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gRoot.setContentsMargins(-1, -1, -1, 21)
        self.gRoot.setObjectName("gRoot")
        self.hCommands = QtWidgets.QHBoxLayout()
        self.hCommands.setContentsMargins(0, 0, 0, 0)
        self.hCommands.setObjectName("hCommands")
        self.leCommand = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leCommand.sizePolicy().hasHeightForWidth())
        self.leCommand.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.leCommand.setFont(font)
        self.leCommand.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.leCommand.setObjectName("leCommand")
        self.hCommands.addWidget(self.leCommand)
        self.bAddCommand = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bAddCommand.sizePolicy().hasHeightForWidth())
        self.bAddCommand.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bAddCommand.setFont(font)
        self.bAddCommand.setObjectName("bAddCommand")
        self.hCommands.addWidget(self.bAddCommand)
        self.gRoot.addLayout(self.hCommands, 3, 0, 1, 1)
        self.teCommands = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.teCommands.sizePolicy().hasHeightForWidth())
        self.teCommands.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.teCommands.setFont(font)
        self.teCommands.setObjectName("teCommands")
        self.gRoot.addWidget(self.teCommands, 3, 1, 1, 1)
        self.gButtons = QtWidgets.QGridLayout()
        self.gButtons.setObjectName("gButtons")
        self.leDistance = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leDistance.sizePolicy().hasHeightForWidth())
        self.leDistance.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.leDistance.setFont(font)
        self.leDistance.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.leDistance.setObjectName("leDistance")
        self.gButtons.addWidget(self.leDistance, 3, 1, 1, 2)
        self.leDegrees = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leDegrees.sizePolicy().hasHeightForWidth())
        self.leDegrees.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.leDegrees.setFont(font)
        self.leDegrees.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.leDegrees.setObjectName("leDegrees")
        self.gButtons.addWidget(self.leDegrees, 4, 1, 1, 2)
        self.bUp_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bUp_2.sizePolicy().hasHeightForWidth())
        self.bUp_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bUp_2.setFont(font)
        self.bUp_2.setAutoRepeat(True)
        self.bUp_2.setAutoRepeatDelay(100)
        self.bUp_2.setObjectName("bUp_2")
        self.gButtons.addWidget(self.bUp_2, 2, 2, 1, 1)
        self.bTurnRight_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bTurnRight_2.sizePolicy().hasHeightForWidth())
        self.bTurnRight_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bTurnRight_2.setFont(font)
        self.bTurnRight_2.setAutoRepeat(True)
        self.bTurnRight_2.setAutoRepeatDelay(100)
        self.bTurnRight_2.setObjectName("bTurnRight_2")
        self.gButtons.addWidget(self.bTurnRight_2, 0, 2, 1, 1)
        self.bBack_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bBack_2.sizePolicy().hasHeightForWidth())
        self.bBack_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bBack_2.setFont(font)
        self.bBack_2.setAutoRepeat(True)
        self.bBack_2.setAutoRepeatDelay(100)
        self.bBack_2.setObjectName("bBack_2")
        self.gButtons.addWidget(self.bBack_2, 2, 1, 1, 1)
        self.bTakeOffLand_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.bTakeOffLand_2.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bTakeOffLand_2.sizePolicy().hasHeightForWidth())
        self.bTakeOffLand_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bTakeOffLand_2.setFont(font)
        self.bTakeOffLand_2.setCheckable(False)
        self.bTakeOffLand_2.setAutoRepeat(True)
        self.bTakeOffLand_2.setAutoRepeatDelay(100)
        self.bTakeOffLand_2.setObjectName("bTakeOffLand_2")
        self.gButtons.addWidget(self.bTakeOffLand_2, 1, 1, 1, 1)
        self.bShtrafeLeft_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bShtrafeLeft_2.sizePolicy().hasHeightForWidth())
        self.bShtrafeLeft_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bShtrafeLeft_2.setFont(font)
        self.bShtrafeLeft_2.setAutoRepeat(True)
        self.bShtrafeLeft_2.setAutoRepeatDelay(100)
        self.bShtrafeLeft_2.setObjectName("bShtrafeLeft_2")
        self.gButtons.addWidget(self.bShtrafeLeft_2, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gButtons.addWidget(self.label_2, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gButtons.addWidget(self.label, 3, 0, 1, 1)
        self.bDown_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bDown_2.sizePolicy().hasHeightForWidth())
        self.bDown_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bDown_2.setFont(font)
        self.bDown_2.setAutoRepeat(True)
        self.bDown_2.setAutoRepeatDelay(100)
        self.bDown_2.setObjectName("bDown_2")
        self.gButtons.addWidget(self.bDown_2, 2, 0, 1, 1)
        self.bStrafeRight_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bStrafeRight_2.sizePolicy().hasHeightForWidth())
        self.bStrafeRight_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bStrafeRight_2.setFont(font)
        self.bStrafeRight_2.setAutoRepeat(True)
        self.bStrafeRight_2.setAutoRepeatDelay(100)
        self.bStrafeRight_2.setObjectName("bStrafeRight_2")
        self.gButtons.addWidget(self.bStrafeRight_2, 1, 2, 1, 1)
        self.bForward_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bForward_2.sizePolicy().hasHeightForWidth())
        self.bForward_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bForward_2.setFont(font)
        self.bForward_2.setAutoRepeat(True)
        self.bForward_2.setAutoRepeatDelay(100)
        self.bForward_2.setObjectName("bForward_2")
        self.gButtons.addWidget(self.bForward_2, 0, 1, 1, 1)
        self.bTurnLeft_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bTurnLeft_2.sizePolicy().hasHeightForWidth())
        self.bTurnLeft_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bTurnLeft_2.setFont(font)
        self.bTurnLeft_2.setAutoRepeat(True)
        self.bTurnLeft_2.setAutoRepeatDelay(100)
        self.bTurnLeft_2.setObjectName("bTurnLeft_2")
        self.gButtons.addWidget(self.bTurnLeft_2, 0, 0, 1, 1)
        self.leSpeed = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leSpeed.sizePolicy().hasHeightForWidth())
        self.leSpeed.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.leSpeed.setFont(font)
        self.leSpeed.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.leSpeed.setObjectName("leSpeed")
        self.gButtons.addWidget(self.leSpeed, 5, 1, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gButtons.addWidget(self.label_3, 5, 0, 1, 1)
        self.gRoot.addLayout(self.gButtons, 1, 0, 1, 1)
        self.gSimulation = QtWidgets.QGridLayout()
        self.gSimulation.setObjectName("gSimulation")
        self.bResetSimulation = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bResetSimulation.setFont(font)
        self.bResetSimulation.setObjectName("bResetSimulation")
        self.gSimulation.addWidget(self.bResetSimulation, 0, 0, 1, 1)
        self.bRunSimulation = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bRunSimulation.setFont(font)
        self.bRunSimulation.setObjectName("bRunSimulation")
        self.gSimulation.addWidget(self.bRunSimulation, 0, 1, 1, 1)
        self.gRoot.addLayout(self.gSimulation, 4, 0, 1, 1)
        self.bPushToDrone = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bPushToDrone.setFont(font)
        self.bPushToDrone.setObjectName("bPushToDrone")
        self.gRoot.addWidget(self.bPushToDrone, 4, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.sbStatusBar = QtWidgets.QStatusBar(MainWindow)
        self.sbStatusBar.setObjectName("sbStatusBar")
        MainWindow.setStatusBar(self.sbStatusBar)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.bTurnLeft_2, QtCore.SIGNAL("clicked()"), MainWindow.on_turn_left)
        QtCore.QObject.connect(self.bForward_2, QtCore.SIGNAL("clicked()"), MainWindow.on_forward)
        QtCore.QObject.connect(self.bTurnRight_2, QtCore.SIGNAL("clicked()"), MainWindow.on_turn_right)
        QtCore.QObject.connect(self.bShtrafeLeft_2, QtCore.SIGNAL("clicked()"), MainWindow.on_strafe_left)
        QtCore.QObject.connect(self.bTakeOffLand_2, QtCore.SIGNAL("clicked()"), MainWindow.on_takeoff_land)
        QtCore.QObject.connect(self.bStrafeRight_2, QtCore.SIGNAL("clicked()"), MainWindow.on_strafe_right)
        QtCore.QObject.connect(self.bDown_2, QtCore.SIGNAL("clicked()"), MainWindow.on_down)
        QtCore.QObject.connect(self.bBack_2, QtCore.SIGNAL("clicked()"), MainWindow.on_back)
        QtCore.QObject.connect(self.bUp_2, QtCore.SIGNAL("clicked()"), MainWindow.on_up)
        QtCore.QObject.connect(self.bAddCommand, QtCore.SIGNAL("clicked()"), MainWindow.on_add_command)
        QtCore.QObject.connect(self.bResetSimulation, QtCore.SIGNAL("clicked()"), MainWindow.on_reset_simulation)
        QtCore.QObject.connect(self.bPushToDrone, QtCore.SIGNAL("clicked()"), MainWindow.on_push_to_drone)
        QtCore.QObject.connect(self.bRunSimulation, QtCore.SIGNAL("clicked()"), MainWindow.on_run_simulation)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Wubalubadubdub", None, -1))
        self.bAddCommand.setText(QtWidgets.QApplication.translate("MainWindow", "Add Command", None, -1))
        self.bAddCommand.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Return", None, -1))
        self.leDistance.setText(QtWidgets.QApplication.translate("MainWindow", "30", None, -1))
        self.leDegrees.setText(QtWidgets.QApplication.translate("MainWindow", "30", None, -1))
        self.bUp_2.setText(QtWidgets.QApplication.translate("MainWindow", "Up", None, -1))
        self.bUp_2.setShortcut(QtWidgets.QApplication.translate("MainWindow", "3", None, -1))
        self.bTurnRight_2.setText(QtWidgets.QApplication.translate("MainWindow", "Turn Right", None, -1))
        self.bTurnRight_2.setShortcut(QtWidgets.QApplication.translate("MainWindow", "9", None, -1))
        self.bBack_2.setText(QtWidgets.QApplication.translate("MainWindow", "Back", None, -1))
        self.bBack_2.setShortcut(QtWidgets.QApplication.translate("MainWindow", "2", None, -1))
        self.bTakeOffLand_2.setText(QtWidgets.QApplication.translate("MainWindow", "Take Off", None, -1))
        self.bTakeOffLand_2.setShortcut(QtWidgets.QApplication.translate("MainWindow", "5", None, -1))
        self.bShtrafeLeft_2.setText(QtWidgets.QApplication.translate("MainWindow", "Strafe Left", None, -1))
        self.bShtrafeLeft_2.setShortcut(QtWidgets.QApplication.translate("MainWindow", "4", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Degrees", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Distance", None, -1))
        self.bDown_2.setText(QtWidgets.QApplication.translate("MainWindow", "Down", None, -1))
        self.bDown_2.setShortcut(QtWidgets.QApplication.translate("MainWindow", "1", None, -1))
        self.bStrafeRight_2.setText(QtWidgets.QApplication.translate("MainWindow", "Strafe Right", None, -1))
        self.bStrafeRight_2.setShortcut(QtWidgets.QApplication.translate("MainWindow", "6", None, -1))
        self.bForward_2.setText(QtWidgets.QApplication.translate("MainWindow", "Forward", None, -1))
        self.bForward_2.setShortcut(QtWidgets.QApplication.translate("MainWindow", "8", None, -1))
        self.bTurnLeft_2.setText(QtWidgets.QApplication.translate("MainWindow", "Turn Left", None, -1))
        self.bTurnLeft_2.setShortcut(QtWidgets.QApplication.translate("MainWindow", "7", None, -1))
        self.leSpeed.setText(QtWidgets.QApplication.translate("MainWindow", "30", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Speed", None, -1))
        self.bResetSimulation.setText(QtWidgets.QApplication.translate("MainWindow", "Reset simulation", None, -1))
        self.bRunSimulation.setText(QtWidgets.QApplication.translate("MainWindow", "Run simulation", None, -1))
        self.bPushToDrone.setText(QtWidgets.QApplication.translate("MainWindow", "Push to Drone", None, -1))

