# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PySide2GUI/ui/WubaGUI.ui',
# licensing of 'PySide2GUI/ui/WubaGUI.ui' applies.
#
# Created: Sat Nov  9 20:13:37 2019
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1080, 720)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1081, 721))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gRoot = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gRoot.setContentsMargins(-1, -1, -1, 21)
        self.gRoot.setObjectName("gRoot")
        self.gButtons = QtWidgets.QGridLayout()
        self.gButtons.setContentsMargins(0, 0, 0, 0)
        self.gButtons.setObjectName("gButtons")
        self.bShtrafeLeft_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bShtrafeLeft_2.sizePolicy().hasHeightForWidth())
        self.bShtrafeLeft_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bShtrafeLeft_2.setFont(font)
        self.bShtrafeLeft_2.setAutoRepeat(True)
        self.bShtrafeLeft_2.setAutoRepeatDelay(100)
        self.bShtrafeLeft_2.setObjectName("bShtrafeLeft_2")
        self.gButtons.addWidget(self.bShtrafeLeft_2, 1, 0, 1, 1)
        self.bTakeOffLand_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bTakeOffLand_2.sizePolicy().hasHeightForWidth())
        self.bTakeOffLand_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bTakeOffLand_2.setFont(font)
        self.bTakeOffLand_2.setCheckable(False)
        self.bTakeOffLand_2.setAutoRepeat(True)
        self.bTakeOffLand_2.setAutoRepeatDelay(100)
        self.bTakeOffLand_2.setObjectName("bTakeOffLand_2")
        self.gButtons.addWidget(self.bTakeOffLand_2, 1, 1, 1, 1)
        self.bTurnLeft_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bTurnLeft_2.sizePolicy().hasHeightForWidth())
        self.bTurnLeft_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bTurnLeft_2.setFont(font)
        self.bTurnLeft_2.setAutoRepeat(True)
        self.bTurnLeft_2.setAutoRepeatDelay(100)
        self.bTurnLeft_2.setObjectName("bTurnLeft_2")
        self.gButtons.addWidget(self.bTurnLeft_2, 0, 0, 1, 1)
        self.bTurnRight_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bTurnRight_2.sizePolicy().hasHeightForWidth())
        self.bTurnRight_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bTurnRight_2.setFont(font)
        self.bTurnRight_2.setAutoRepeat(True)
        self.bTurnRight_2.setAutoRepeatDelay(100)
        self.bTurnRight_2.setObjectName("bTurnRight_2")
        self.gButtons.addWidget(self.bTurnRight_2, 0, 2, 1, 1)
        self.bDown_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bDown_2.sizePolicy().hasHeightForWidth())
        self.bDown_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bDown_2.setFont(font)
        self.bDown_2.setAutoRepeat(True)
        self.bDown_2.setAutoRepeatDelay(100)
        self.bDown_2.setObjectName("bDown_2")
        self.gButtons.addWidget(self.bDown_2, 2, 0, 1, 1)
        self.bPitchUp = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bPitchUp.sizePolicy().hasHeightForWidth())
        self.bPitchUp.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bPitchUp.setFont(font)
        self.bPitchUp.setAutoRepeat(True)
        self.bPitchUp.setAutoRepeatDelay(100)
        self.bPitchUp.setObjectName("bPitchUp")
        self.gButtons.addWidget(self.bPitchUp, 3, 0, 1, 1)
        self.bStrafeRight_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bStrafeRight_2.sizePolicy().hasHeightForWidth())
        self.bStrafeRight_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bStrafeRight_2.setFont(font)
        self.bStrafeRight_2.setAutoRepeat(True)
        self.bStrafeRight_2.setAutoRepeatDelay(100)
        self.bStrafeRight_2.setObjectName("bStrafeRight_2")
        self.gButtons.addWidget(self.bStrafeRight_2, 1, 2, 1, 1)
        self.bBack_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bBack_2.sizePolicy().hasHeightForWidth())
        self.bBack_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bBack_2.setFont(font)
        self.bBack_2.setAutoRepeat(True)
        self.bBack_2.setAutoRepeatDelay(100)
        self.bBack_2.setObjectName("bBack_2")
        self.gButtons.addWidget(self.bBack_2, 2, 1, 1, 1)
        self.bPitchDown = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bPitchDown.sizePolicy().hasHeightForWidth())
        self.bPitchDown.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bPitchDown.setFont(font)
        self.bPitchDown.setAutoRepeat(True)
        self.bPitchDown.setAutoRepeatDelay(100)
        self.bPitchDown.setObjectName("bPitchDown")
        self.gButtons.addWidget(self.bPitchDown, 3, 2, 1, 1)
        self.bPitchReset = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bPitchReset.sizePolicy().hasHeightForWidth())
        self.bPitchReset.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bPitchReset.setFont(font)
        self.bPitchReset.setAutoRepeat(True)
        self.bPitchReset.setAutoRepeatDelay(100)
        self.bPitchReset.setObjectName("bPitchReset")
        self.gButtons.addWidget(self.bPitchReset, 3, 1, 1, 1)
        self.bForward_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bForward_2.sizePolicy().hasHeightForWidth())
        self.bForward_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bForward_2.setFont(font)
        self.bForward_2.setAutoRepeat(True)
        self.bForward_2.setAutoRepeatDelay(100)
        self.bForward_2.setObjectName("bForward_2")
        self.gButtons.addWidget(self.bForward_2, 0, 1, 1, 1)
        self.bUp_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bUp_2.sizePolicy().hasHeightForWidth())
        self.bUp_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bUp_2.setFont(font)
        self.bUp_2.setAutoRepeat(True)
        self.bUp_2.setAutoRepeatDelay(100)
        self.bUp_2.setObjectName("bUp_2")
        self.gButtons.addWidget(self.bUp_2, 2, 2, 1, 1)
        self.leSpeed = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leSpeed.sizePolicy().hasHeightForWidth())
        self.leSpeed.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.leSpeed.setFont(font)
        self.leSpeed.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.leSpeed.setObjectName("leSpeed")
        self.gButtons.addWidget(self.leSpeed, 4, 1, 1, 2)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gButtons.addWidget(self.label, 4, 0, 1, 1)
        self.gRoot.addLayout(self.gButtons, 1, 0, 1, 1)
        self.teCommands = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.teCommands.sizePolicy().hasHeightForWidth())
        self.teCommands.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.teCommands.setFont(font)
        self.teCommands.setObjectName("teCommands")
        self.gRoot.addWidget(self.teCommands, 2, 1, 1, 1)
        self.hCommands = QtWidgets.QHBoxLayout()
        self.hCommands.setObjectName("hCommands")
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.hCommands.addWidget(self.lineEdit)
        self.bAddCommand = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bAddCommand.sizePolicy().hasHeightForWidth())
        self.bAddCommand.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bAddCommand.setFont(font)
        self.bAddCommand.setObjectName("bAddCommand")
        self.hCommands.addWidget(self.bAddCommand)
        self.gRoot.addLayout(self.hCommands, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.sbStatusBar = QtWidgets.QStatusBar(MainWindow)
        self.sbStatusBar.setObjectName("sbStatusBar")
        MainWindow.setStatusBar(self.sbStatusBar)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.bTurnLeft_2, QtCore.SIGNAL("clicked()"), MainWindow.on_turn_left)
        QtCore.QObject.connect(self.bForward_2, QtCore.SIGNAL("clicked()"), MainWindow.on_forward)
        QtCore.QObject.connect(self.bTurnRight_2, QtCore.SIGNAL("clicked()"), MainWindow.on_turn_right)
        QtCore.QObject.connect(self.bShtrafeLeft_2, QtCore.SIGNAL("clicked()"), MainWindow.on_strafe_left)
        QtCore.QObject.connect(self.bTakeOffLand_2, QtCore.SIGNAL("clicked()"), MainWindow.on_takeoff_land)
        QtCore.QObject.connect(self.bStrafeRight_2, QtCore.SIGNAL("clicked()"), MainWindow.on_strafe_right)
        QtCore.QObject.connect(self.bDown_2, QtCore.SIGNAL("clicked()"), MainWindow.on_down)
        QtCore.QObject.connect(self.bBack_2, QtCore.SIGNAL("clicked()"), MainWindow.on_back)
        QtCore.QObject.connect(self.bUp_2, QtCore.SIGNAL("clicked()"), MainWindow.on_up)
        QtCore.QObject.connect(self.bAddCommand, QtCore.SIGNAL("clicked()"), MainWindow.on_add_command)
        QtCore.QObject.connect(self.bPitchUp, QtCore.SIGNAL("clicked()"), MainWindow.on_pitch_up)
        QtCore.QObject.connect(self.bPitchReset, QtCore.SIGNAL("clicked()"), MainWindow.on_pitch_reset)
        QtCore.QObject.connect(self.bPitchDown, QtCore.SIGNAL("clicked()"), MainWindow.on_pitch_down)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Wubalubadubdub", None, -1))
        self.bShtrafeLeft_2.setText(QtWidgets.QApplication.translate("MainWindow", "Strafe Left", None, -1))
        self.bShtrafeLeft_2.setShortcut(QtWidgets.QApplication.translate("MainWindow", "4", None, -1))
        self.bTakeOffLand_2.setText(QtWidgets.QApplication.translate("MainWindow", "TakeOff / Land", None, -1))
        self.bTakeOffLand_2.setShortcut(QtWidgets.QApplication.translate("MainWindow", "5", None, -1))
        self.bTurnLeft_2.setText(QtWidgets.QApplication.translate("MainWindow", "Turn Left", None, -1))
        self.bTurnLeft_2.setShortcut(QtWidgets.QApplication.translate("MainWindow", "7", None, -1))
        self.bTurnRight_2.setText(QtWidgets.QApplication.translate("MainWindow", "Turn Right", None, -1))
        self.bTurnRight_2.setShortcut(QtWidgets.QApplication.translate("MainWindow", "9", None, -1))
        self.bDown_2.setText(QtWidgets.QApplication.translate("MainWindow", "Down", None, -1))
        self.bDown_2.setShortcut(QtWidgets.QApplication.translate("MainWindow", "1", None, -1))
        self.bPitchUp.setText(QtWidgets.QApplication.translate("MainWindow", "Pitch Up", None, -1))
        self.bStrafeRight_2.setText(QtWidgets.QApplication.translate("MainWindow", "Strafe Right", None, -1))
        self.bStrafeRight_2.setShortcut(QtWidgets.QApplication.translate("MainWindow", "6", None, -1))
        self.bBack_2.setText(QtWidgets.QApplication.translate("MainWindow", "Back", None, -1))
        self.bBack_2.setShortcut(QtWidgets.QApplication.translate("MainWindow", "2", None, -1))
        self.bPitchDown.setText(QtWidgets.QApplication.translate("MainWindow", "Pitch Down", None, -1))
        self.bPitchReset.setText(QtWidgets.QApplication.translate("MainWindow", "Pitch Reset", None, -1))
        self.bForward_2.setText(QtWidgets.QApplication.translate("MainWindow", "Forward", None, -1))
        self.bForward_2.setShortcut(QtWidgets.QApplication.translate("MainWindow", "8", None, -1))
        self.bUp_2.setText(QtWidgets.QApplication.translate("MainWindow", "Up", None, -1))
        self.bUp_2.setShortcut(QtWidgets.QApplication.translate("MainWindow", "3", None, -1))
        self.leSpeed.setText(QtWidgets.QApplication.translate("MainWindow", "60", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Speed", None, -1))
        self.bAddCommand.setText(QtWidgets.QApplication.translate("MainWindow", "Add Command", None, -1))
        self.bAddCommand.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Return", None, -1))

